### ISSUE TITLE
Flushing cache for yum repo sometimes fails, causing build script to end prematuarlly

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#128]
```
Cleaning release/11-kasparov-nightly:
Purging the cache for files that were uploaded
/root/.gem/ruby/gems/droplet_kit-3.12.0/lib/droplet_kit/error_handling_resourcable.rb:14:in `block (2 levels) in included': 500: {"id": "Internal Server Error", "message": "Server Error" } (DropletKit::Error)
        from /root/.gem/ruby/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `instance_exec'
        from /root/.gem/ruby/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:19:in `handle_response'
        from /root/.gem/ruby/gems/resource_kit-0.1.7/lib/resource_kit/action_invoker.rb:14:in `call'
        from /root/.gem/ruby/gems/resource_kit-0.1.7/lib/resource_kit/method_factory.rb:16:in `block in method_for_action'
        from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:82:in `block in update'
        from /usr/share/ruby/tmpdir.rb:93:in `mktmpdir'
        from /build_scripts/lib/manageiq/rpm_build/rpm_repo.rb:9:in `update'
        from bin/build.rb:52:in `<main>'
Command exited with non-zero status 1
```

**Comment by simaishi** [comment]
cc @bdunne
